version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: lacrei
      POSTGRES_PASSWORD: sua_senha_segura
      POSTGRES_DB: lacreisaude
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    command: sh -c "python manage.py migrate && gunicorn lacreisaude.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://lacrei:sua_senha_segura@db:5432/lacreisaude
volumes:
  db_data:
