name: Deploy

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Deploy to Staging
      if: github.ref == 'refs/heads/staging'
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST_STAGING }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /caminho/da/app
          git pull origin staging
          docker-compose down
          docker-compose up -d --build

    - name: Deploy to Production
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST_PRODUCTION }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /caminho/da/app
          git pull origin main
          docker-compose down
          docker-compose up -d --build
